export const GET_LIST = "GET_LIST";
export const SELECT_CARD = "SELECT_CARD";
export const DESELECT_CARD = "DESELECT_CARD";

export const REQUEST_CARD = "REQUEST_CARD";
export const REQUEST_ADD_CARD = "REQUEST_ADD_CARD";
export const REQUEST_REMOVE_CARD = "REQUEST_REMOVE_CARD";
